# Generated by Django 3.0.4 on 2020-03-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0002_auto_20200307_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprofile',
            name='patient',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_profile',
            field=models.ManyToManyField(to='doctorapp.MedicalProfile'),
        ),
    ]
