# Generated by Django 3.0.4 on 2020-03-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_auto_20200307_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='patient',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(to='doctorapp.Location'),
        ),
    ]
