# Generated by Django 3.0.4 on 2020-03-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_auto_20200307_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='disease',
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.ManyToManyField(to='doctorapp.Symptom'),
        ),
    ]
