# Generated by Django 3.0.4 on 2020-03-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0005_auto_20200307_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='specialization',
        ),
        migrations.AddField(
            model_name='specialization',
            name='disease',
            field=models.ManyToManyField(to='doctorapp.Disease'),
        ),
    ]
