# Generated by Django 3.0.4 on 2020-03-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_auto_20200307_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='doctor',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ManyToManyField(to='doctorapp.Specialization'),
        ),
    ]
