# Generated by Django 3.0.4 on 2020-03-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0007_auto_20200307_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
