# Generated by Django 3.0.4 on 2020-03-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0008_auto_20200307_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAttached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('infection_image', models.FileField(blank=True, null=True, upload_to='attachment_%y_%m_%d')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctorapp.MedicalProfile')),
            ],
        ),
    ]
