# Generated by Django 3.0.4 on 2020-03-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0009_filesattached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
